### ISSUE TITLE
$HOME user is set as $GITHUB_ACTOR rather than jovyan

### ISSUE THREAD

**Issue by psychemedia** [machine-learning-apps/repo2docker-action#11]
The user account used when calling `repo2docker` is the `$GITHUB_ACTOR` account rather than the `jovyan` default used in MyBinder: https://github.com/machine-learning-apps/repo2docker-action/blob/1c58b645fec7f2cb708fd50e53c4da76f5b410fb/create_docker_image.sh#L27

This leaks information about the repo used to create the container, and also creates a difference between between the container using MyBinder and pulling and running the pushed image.

**Comment by neovintage** [comment]
@psychemedia Thanks for pointing this out. I'll try to get to get it fixed.

**Comment by neovintage** [comment]
Thinking about this a bit more, we can make `user-name` configurable. This way if someone wants to use MyBinder they can do so or they can use their own user names within whatever target environment they have set up.

**Comment by psychemedia** [comment]
That would make sense, I think. I have a fork [here](https://github.com/machine-learning-apps/repo2docker-action/compare/master...ouseful-PR:master) that currently hardwires in the `jovyan` user, and also pushes the built container with a `latest` tag which makes it easier to pull on (I generally call the action with an `on: release` selector; on to do list was to tweak the action so if the commit was a release, only then would a `latest` tag push be fired).

**Comment by neovintage** [comment]
@psychemedia just merged a fix. closing this issue out.
