### ISSUE TITLE
Tagging images

### ISSUE THREAD

**Issue by psychemedia** [machine-learning-apps/repo2docker-action#9]
Really useful action, thanks....

Is there a way of specifying particular tags that the image is pushed to Docker Hub with?

By default the tag seems to be a hash, rather than `latest` or a user customised value?

If I set `IMAGE_NAME: "user/repo:tag"` then it raises an error as:

`jupyter-repo2docker: error: argument --image-name: 'user/repo:tag:HASH'`

using the automatically created `HASH` value as "another" tag.

**Comment by psychemedia** [comment]
A possible workaround to keep the hash tagged image as well as building a `latest` tagged image would be to add after https://github.com/machine-learning-apps/repo2docker-action/blob/1c58b645fec7f2cb708fd50e53c4da76f5b410fb/create_docker_image.sh#L31 something like:

```
LATEST_NAME="${INPUT_IMAGE_NAME}:latest"
echo "docker push ${LATEST_NAME}"
docker push ${LATEST_NAME}
```

**Comment by hamelsmu** [comment]
This is a good suggestion, I will work on this
